Navbar blijft nu gehighlight als je op de pagina bent. De volgende ke…
Proteus-Eretes/hswi2 pull request #79
Opened 2022-12-04 18:25 UTC by Dux02

…er kijken of de logica werkend ook compacter kan heb ook placeholders voor de uitslagen en lotingen geplaatst

2022-12-04 18:39 UTC, Dux02 commented
Ik krijg de error 500 window is not defined als ik een pagina opnieuw probeer te laden... Dus zou hem niet pushen

2022-12-07 22:04 UTC, Gerbuuun requested changes

2022-12-07 22:04 UTC, Gerbuuun commented on layouts/navigation.vue
> +});
Zoek op vuejs documentatie naar `ref`
Dat is de standaard ipv `let`

2022-12-07 22:04 UTC, Gerbuuun commented on layouts/navigation.vue
> +            class="tab tab-lg hover:border-base-300 hover:border-b-4"
Kijk of die classes niet dubbel kan

2022-12-08 11:23 UTC, Dux02 commented on layouts/navigation.vue
> +            class="tab tab-lg hover:border-base-300 hover:border-b-4"
Deze is done

2023-01-25 19:34 UTC, closed without merging